# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mutex_pb2 as mutex__pb2


class MutexCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.request_cs = channel.unary_unary(
                '/MutexCommunicator/request_cs',
                request_serializer=mutex__pb2.MutexRequest.SerializeToString,
                response_deserializer=mutex__pb2.MutexResponse.FromString,
                )


class MutexCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def request_cs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutexCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'request_cs': grpc.unary_unary_rpc_method_handler(
                    servicer.request_cs,
                    request_deserializer=mutex__pb2.MutexRequest.FromString,
                    response_serializer=mutex__pb2.MutexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MutexCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MutexCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def request_cs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MutexCommunicator/request_cs',
            mutex__pb2.MutexRequest.SerializeToString,
            mutex__pb2.MutexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
