# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mutex.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmutex.proto\"/\n\x0cMutexRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\x05\"\x1d\n\rMutexResponse\x12\x0c\n\x04name\x18\x01 \x02(\t2@\n\x11MutexCommunicator\x12+\n\nrequest_cs\x12\r.MutexRequest\x1a\x0e.MutexResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mutex_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MUTEXREQUEST']._serialized_start=15
  _globals['_MUTEXREQUEST']._serialized_end=62
  _globals['_MUTEXRESPONSE']._serialized_start=64
  _globals['_MUTEXRESPONSE']._serialized_end=93
  _globals['_MUTEXCOMMUNICATOR']._serialized_start=95
  _globals['_MUTEXCOMMUNICATOR']._serialized_end=159
# @@protoc_insertion_point(module_scope)
