# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x0bmediaprotos\"9\n\x0ePublishRequest\x12\x11\n\tfile_name\x18\x01 \x02(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x02(\x0c\"#\n\x0fPublishResponse\x12\x10\n\x08response\x18\x01 \x02(\t\"6\n\x0e\x43ontentRequest\x12\x11\n\tfile_name\x18\x01 \x02(\t\x12\x11\n\tclient_ip\x18\x02 \x02(\t\"J\n\x0f\x43ontentResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x02(\x0c\x12\x0e\n\x06status\x18\x02 \x02(\x05\x12\x11\n\tserver_ip\x18\x03 \x02(\t\"3\n\x0b\x46ileRequest\x12\x11\n\tfile_name\x18\x01 \x02(\t\x12\x11\n\tclient_ip\x18\x02 \x02(\t\"1\n\x0c\x46ileResponse\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x11\n\tserver_ip\x18\x02 \x02(\t2\xec\x01\n\x0cMediaLibrary\x12G\n\ngetContent\x12\x1b.mediaprotos.ContentRequest\x1a\x1c.mediaprotos.ContentResponse\x12K\n\x0epublishContent\x12\x1b.mediaprotos.PublishRequest\x1a\x1c.mediaprotos.PublishResponse\x12\x46\n\x0f\x63heckFileExists\x12\x18.mediaprotos.FileRequest\x1a\x19.mediaprotos.FileResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUBLISHREQUEST']._serialized_start=29
  _globals['_PUBLISHREQUEST']._serialized_end=86
  _globals['_PUBLISHRESPONSE']._serialized_start=88
  _globals['_PUBLISHRESPONSE']._serialized_end=123
  _globals['_CONTENTREQUEST']._serialized_start=125
  _globals['_CONTENTREQUEST']._serialized_end=179
  _globals['_CONTENTRESPONSE']._serialized_start=181
  _globals['_CONTENTRESPONSE']._serialized_end=255
  _globals['_FILEREQUEST']._serialized_start=257
  _globals['_FILEREQUEST']._serialized_end=308
  _globals['_FILERESPONSE']._serialized_start=310
  _globals['_FILERESPONSE']._serialized_end=359
  _globals['_MEDIALIBRARY']._serialized_start=362
  _globals['_MEDIALIBRARY']._serialized_end=598
# @@protoc_insertion_point(module_scope)
