# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class MediaLibraryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getContent = channel.unary_unary(
                '/mediaprotos.MediaLibrary/getContent',
                request_serializer=server__pb2.ContentRequest.SerializeToString,
                response_deserializer=server__pb2.ContentResponse.FromString,
                )
        self.publishContent = channel.unary_unary(
                '/mediaprotos.MediaLibrary/publishContent',
                request_serializer=server__pb2.PublishRequest.SerializeToString,
                response_deserializer=server__pb2.PublishResponse.FromString,
                )
        self.checkFileExists = channel.unary_unary(
                '/mediaprotos.MediaLibrary/checkFileExists',
                request_serializer=server__pb2.FileRequest.SerializeToString,
                response_deserializer=server__pb2.FileResponse.FromString,
                )


class MediaLibraryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def publishContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkFileExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaLibraryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getContent': grpc.unary_unary_rpc_method_handler(
                    servicer.getContent,
                    request_deserializer=server__pb2.ContentRequest.FromString,
                    response_serializer=server__pb2.ContentResponse.SerializeToString,
            ),
            'publishContent': grpc.unary_unary_rpc_method_handler(
                    servicer.publishContent,
                    request_deserializer=server__pb2.PublishRequest.FromString,
                    response_serializer=server__pb2.PublishResponse.SerializeToString,
            ),
            'checkFileExists': grpc.unary_unary_rpc_method_handler(
                    servicer.checkFileExists,
                    request_deserializer=server__pb2.FileRequest.FromString,
                    response_serializer=server__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mediaprotos.MediaLibrary', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MediaLibrary(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediaprotos.MediaLibrary/getContent',
            server__pb2.ContentRequest.SerializeToString,
            server__pb2.ContentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def publishContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediaprotos.MediaLibrary/publishContent',
            server__pb2.PublishRequest.SerializeToString,
            server__pb2.PublishResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkFileExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediaprotos.MediaLibrary/checkFileExists',
            server__pb2.FileRequest.SerializeToString,
            server__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
